'use client'

/**
 * document-list — the document table/list.
 *
 * Refined library-style table with subtle row hover, small file-type icons,
 * source + format badges, and per-row Preview / Download / More actions.
 *
 * Click anywhere on the row (outside the actions) opens the detail drawer.
 */

import { useMemo } from 'react'
import { motion } from 'framer-motion'
import {
  Eye, Download, MoreHorizontal, FileCheck2, Search, X,
  RotateCcw, Printer, Share2, Star, Info,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu, DropdownMenuTrigger, DropdownMenuContent,
  DropdownMenuItem, DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu'
import { formatDate, formatRelativeTime } from '@/lib/format'
import {
  useDownloadsStore,
  type DownloadDocument,
} from '@/lib/store/downloads-store'
import {
  SourceBadge, CategoryPill,
  DownloadsEmptyState, docDescriptionLabel,
} from './downloads-shared'
import { useDownloadsActions } from './downloads-actions'
import {
  DocumentThumbnail, FileTypeBadge,
} from '@/components/shared/document-primitives'
import type { DocFormat } from '@/components/shared/document-primitives'

interface DocumentListProps {
  onSelectDoc: (doc: DownloadDocument) => void
}

export function DocumentList({ onSelectDoc }: DocumentListProps) {
  const getFilteredDocuments = useDownloadsStore((s) => s.getFilteredDocuments)
  const recordPreview = useDownloadsStore((s) => s.recordPreview)
  const resetFilters = useDownloadsStore((s) => s.resetFilters)
  const query = useDownloadsStore((s) => s.query)
  const categoryFilter = useDownloadsStore((s) => s.categoryFilter)
  const categoryTab = useDownloadsStore((s) => s.categoryTab)
  const sortBy = useDownloadsStore((s) => s.sortBy)
  // Shared REAL action implementations (download produces a file, print
  // opens a document window, share uses the Web Share API, pin persists).
  const { handleDownload, handlePrint, handleShare, handleFavourite, handleRegenerate } =
    useDownloadsActions()

  const docs = useMemo(
    () => getFilteredDocuments(),
    [getFilteredDocuments, query, categoryFilter, categoryTab, sortBy],
  )

  function onDownload(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    handleDownload(doc)
  }

  function handlePreview(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    recordPreview(doc)
    onSelectDoc(doc)
  }

  function onPrint(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    handlePrint(doc)
  }

  function onShare(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    void handleShare(doc)
  }

  function onPin(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    handleFavourite(doc)
  }

  function onRegenerate(doc: DownloadDocument, e?: React.MouseEvent) {
    e?.stopPropagation()
    handleRegenerate(doc)
  }

  if (docs.length === 0) {
    const filtered = (query.trim().length > 0) || (categoryFilter !== 'All') || (categoryTab !== 'All')
    return (
      <DownloadsEmptyState
        icon={filtered ? <Search className="h-5 w-5" /> : <FileCheck2 className="h-5 w-5" />}
        title={filtered ? 'No documents match the filters' : 'No documents yet'}
        description={
          filtered
            ? 'Try a different search term, clear the category filter, or switch tabs.'
            : 'Documents generated by the system will appear here automatically.'
        }
        action={
          filtered ? (
            <Button variant="outline" size="sm" onClick={resetFilters} className="h-8 text-xs gap-1.5">
              <X className="h-3.5 w-3.5" /> Clear filters
            </Button>
          ) : undefined
        }
      />
    )
  }

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden">
      {/* Desktop (md+) — refined library-style table */}
      <div className="hidden md:block overflow-x-auto downloads-list-scroll">
        <table className="w-full text-xs min-w-[680px] [&_td]:py-3">
          <thead>
            <tr className="border-b border-border bg-muted/30 text-[10px] uppercase tracking-wider text-muted-foreground">
              <th className="text-left font-semibold px-3 py-2.5 w-[46%]">Document</th>
              <th className="text-left font-semibold px-3 py-2.5">Category</th>
              <th className="text-left font-semibold px-3 py-2.5">Source</th>
              <th className="text-left font-semibold px-3 py-2.5 whitespace-nowrap">Updated</th>
              <th className="text-right font-semibold px-3 py-2.5">Actions</th>
            </tr>
          </thead>
          <tbody>
            {docs.map((doc, i) => {
              const isGenerated = doc.source === 'Generated'
              return (
                <motion.tr
                  key={doc.id}
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.18, delay: Math.min(i * 0.012, 0.18) }}
                  onClick={() => onSelectDoc(doc)}
                  className={cn(
                    'group border-b border-border/40 last:border-b-0 cursor-pointer transition-colors',
                    'hover:bg-emerald-50/40 dark:hover:bg-emerald-500/[0.04]',
                  )}
                >
                  {/* Document cell — DocumentThumbnail (md, paper silhouette +
                      format edge stripe + dog-ear fold) + FileTypeBadge grouped
                      right under the name. The document identity (thumbnail +
                      format badge) is consolidated in one column so the user
                      reads it as a single document, not scattered across cells. */}
                  <td className="px-3 py-3">
                    <div className="flex items-center gap-3 min-w-0">
                      <DocumentThumbnail format={doc.format as DocFormat} size="md" />
                      <div className="min-w-0 flex-1">
                        <p className="font-semibold text-foreground leading-tight truncate">
                          {doc.name}
                        </p>
                        <div className="flex items-center gap-1.5 mt-0.5">
                          <FileTypeBadge format={doc.format as DocFormat} size="xs" />
                          <span className="text-[10px] text-muted-foreground truncate">
                            {docDescriptionLabel(doc)}
                            {doc.size && (
                              <>
                                <span className="text-muted-foreground/40 mx-1">·</span>
                                <span className="tabular-nums">{doc.size}</span>
                              </>
                            )}
                          </span>
                        </div>
                      </div>
                    </div>
                  </td>

                  {/* Category */}
                  <td className="px-3 py-3">
                    <CategoryPill category={doc.category} />
                  </td>

                  {/* Source */}
                  <td className="px-3 py-3">
                    <SourceBadge source={doc.source} />
                  </td>

                  {/* Updated date */}
                  <td className="px-3 py-3 text-[10px] text-muted-foreground whitespace-nowrap">
                    <span className="block font-medium text-foreground/80">
                      {formatRelativeTime(doc.updatedDate)}
                    </span>
                    <span className="block text-[9px] text-muted-foreground/70 tabular-nums">
                      {formatDate(doc.updatedDate)}
                    </span>
                  </td>

                  {/* Actions */}
                  <td className="px-3 py-3">
                    <RowActions
                      doc={doc}
                      isGenerated={isGenerated}
                      onSelectDoc={onSelectDoc}
                      onPreview={handlePreview}
                      onDownload={onDownload}
                      onPrint={onPrint}
                      onShare={onShare}
                      onPin={onPin}
                      onRegenerate={onRegenerate}
                    />
                  </td>
                </motion.tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Mobile (<md) — the table transforms into readable document cards:
          thumbnail + name + format badge + description on top, a compact
          meta row (category · source · updated) below, and the same action
          trio right-aligned. No horizontal scrolling. */}
      <div className="md:hidden divide-y divide-border/60">
        {docs.map((doc, i) => {
          const isGenerated = doc.source === 'Generated'
          return (
            <motion.div
              key={doc.id}
              initial={{ opacity: 0, y: 4 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.18, delay: Math.min(i * 0.012, 0.18) }}
              onClick={() => onSelectDoc(doc)}
              className="p-3 cursor-pointer active:bg-muted/40 transition-colors"
            >
              <div className="flex items-start gap-3 min-w-0">
                <DocumentThumbnail format={doc.format as DocFormat} size="md" />
                <div className="min-w-0 flex-1">
                  <p className="font-semibold text-foreground leading-tight truncate">
                    {doc.name}
                  </p>
                  <div className="flex items-center gap-1.5 mt-1 min-w-0">
                    <FileTypeBadge format={doc.format as DocFormat} size="xs" />
                    <span className="text-[10px] text-muted-foreground truncate">
                      {doc.size ?? docDescriptionLabel(doc)}
                    </span>
                  </div>
                  <p className="text-[10px] text-muted-foreground mt-1.5 truncate">
                    {doc.category} · {doc.source} · {formatRelativeTime(doc.updatedDate)}
                  </p>
                </div>
                {/* Touch-friendly action column — same handlers as desktop */}
                <div className="shrink-0" onClick={(e) => e.stopPropagation()}>
                  <MobileActions
                    doc={doc}
                    isGenerated={isGenerated}
                    onSelectDoc={onSelectDoc}
                    onPreview={handlePreview}
                    onDownload={onDownload}
                    onPrint={onPrint}
                    onShare={onShare}
                    onPin={onPin}
                    onRegenerate={onRegenerate}
                  />
                </div>
              </div>
            </motion.div>
          )
        })}
      </div>

      {/* Footer summary line */}
      <div className="flex items-center justify-between px-3 py-2 border-t border-border/60 bg-muted/20 text-[10px] text-muted-foreground">
        <span>
          Showing <strong className="text-foreground tabular-nums">{docs.length}</strong>{' '}
          {docs.length === 1 ? 'document' : 'documents'}
        </span>
        <span className="hidden sm:inline-flex items-center gap-1.5">
          <span className="tabular-nums">{docs.filter((d) => d.source === 'Generated').length}</span> generated
          <span className="text-muted-foreground/40">·</span>
          <span className="tabular-nums">{docs.filter((d) => d.source === 'Official Form').length}</span> forms
          <span className="text-muted-foreground/40">·</span>
          <span className="tabular-nums">{docs.filter((d) => d.source === 'Template').length}</span> templates
        </span>
      </div>
    </div>
  )
}

// ─── Row actions (desktop) ───────────────────────────────────────────
//
// Consistent h-7 ghost icon buttons — Preview · Download (emerald hover,
// the module's primary per-row action) · More (overflow). Every button
// carries a title tooltip + aria-label.

interface RowActionsProps {
  doc: DownloadDocument
  isGenerated: boolean
  onSelectDoc: (doc: DownloadDocument) => void
  onPreview: (doc: DownloadDocument, e?: React.MouseEvent) => void
  onDownload: (doc: DownloadDocument, e?: React.MouseEvent) => void
  onPrint: (doc: DownloadDocument, e?: React.MouseEvent) => void
  onShare: (doc: DownloadDocument, e?: React.MouseEvent) => void
  onPin: (doc: DownloadDocument, e?: React.MouseEvent) => void
  onRegenerate: (doc: DownloadDocument, e?: React.MouseEvent) => void
}

function RowActions({
  doc, isGenerated, onSelectDoc,
  onPreview, onDownload, onPrint, onShare, onPin, onRegenerate,
}: RowActionsProps) {
  return (
    <div className="flex items-center justify-end gap-0.5">
      <Button
        variant="ghost" size="sm"
        className="h-7 w-7 p-0 text-muted-foreground hover:text-foreground"
        onClick={(e) => onPreview(doc, e)}
        title="Preview"
        aria-label={`Preview ${doc.name}`}
      >
        <Eye className="h-3.5 w-3.5" />
      </Button>
      <Button
        variant="ghost" size="sm"
        className="h-7 w-7 p-0 text-muted-foreground hover:text-emerald-600 dark:hover:text-emerald-400"
        onClick={(e) => onDownload(doc, e)}
        title="Download"
        aria-label={`Download ${doc.name}`}
      >
        <Download className="h-3.5 w-3.5" />
      </Button>
      <OverflowMenu
        doc={doc}
        isGenerated={isGenerated}
        onSelectDoc={onSelectDoc}
        onPreview={onPreview}
        onDownload={onDownload}
        onPrint={onPrint}
        onShare={onShare}
        onPin={onPin}
        onRegenerate={onRegenerate}
      />
    </div>
  )
}

// ─── Row actions (mobile) ────────────────────────────────────────────
// Touch-friendly vertical stack: Download first (primary), Preview, More.

function MobileActions(props: RowActionsProps) {
  const { doc, onDownload, onPreview } = props
  return (
    <div className="flex flex-col items-center gap-1">
      <Button
        variant="ghost" size="sm"
        className="h-8 w-8 p-0 text-muted-foreground hover:text-emerald-600 dark:hover:text-emerald-400"
        onClick={(e) => onDownload(doc, e)}
        title="Download"
        aria-label={`Download ${doc.name}`}
      >
        <Download className="h-4 w-4" />
      </Button>
      <Button
        variant="ghost" size="sm"
        className="h-8 w-8 p-0 text-muted-foreground hover:text-foreground"
        onClick={(e) => onPreview(doc, e)}
        title="Preview"
        aria-label={`Preview ${doc.name}`}
      >
        <Eye className="h-4 w-4" />
      </Button>
      <OverflowMenu {...props} mobile />
    </div>
  )
}

// ─── Shared overflow menu (Preview/Download/Print/Share/Pin/…) ───────

function OverflowMenu({
  doc, isGenerated, onSelectDoc, mobile,
  onPreview, onDownload, onPrint, onShare, onPin, onRegenerate,
}: RowActionsProps & { mobile?: boolean }) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="ghost" size="sm"
          className={cn(
            'p-0 text-muted-foreground hover:text-foreground',
            mobile ? 'h-8 w-8' : 'h-7 w-7',
          )}
          onClick={(e) => e.stopPropagation()}
          title="More actions"
          aria-label={`More actions for ${doc.name}`}
        >
          <MoreHorizontal className={mobile ? 'h-4 w-4' : 'h-3.5 w-3.5'} />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-44 text-xs">
        <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onPreview(doc) }}>
          <Eye className="h-3.5 w-3.5 mr-1.5" /> Preview
        </DropdownMenuItem>
        <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onDownload(doc) }}>
          <Download className="h-3.5 w-3.5 mr-1.5" /> Download
        </DropdownMenuItem>
        <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onPrint(doc) }}>
          <Printer className="h-3.5 w-3.5 mr-1.5" /> Print
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onShare(doc) }}>
          <Share2 className="h-3.5 w-3.5 mr-1.5" /> Copy share link
        </DropdownMenuItem>
        <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onPin(doc) }}>
          <Star className="h-3.5 w-3.5 mr-1.5" /> Add to favourites
        </DropdownMenuItem>
        {isGenerated && doc.docNumber && (
          <>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onRegenerate(doc) }}>
              <RotateCcw className="h-3.5 w-3.5 mr-1.5" /> Regenerate
            </DropdownMenuItem>
            <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onSelectDoc(doc) }}>
              <Info className="h-3.5 w-3.5 mr-1.5" /> View record
            </DropdownMenuItem>
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
