import { assertSeedable } from './seed-guard'
import { DEMO_TRANSFORM_CONSENT_LITERAL } from './seed-guard'
import {
  CLEAN_SCHOOL_SLUG,
  DEMO_SCHOOL_CODE,
  DEMO_SCHOOL_DOMAIN,
  DEMO_SCHOOL_NAME,
  DEMO_SCHOOL_SLUG,
  DEMO_STUDENT_POSITION,
  DEMO_SUBSCRIPTION_LOCKED_STUDENTS,
  DEMO_SUBSCRIPTION_LOCKED_TEACHER_N,
} from './seed-identity'
import {
  buildStudentRoster,
  FACULTY,
  MANAGEMENT,
  PRINCIPAL,
  SPECIAL_ROOMS,
  SUBJECTS,
} from './hawkings-corpus'
import { DEMO_CLASS_LEVELS } from './seed-identity'
import {
  SEED_DEMO_PASSWORD,
  SEED_SHOWCASE_PRINCIPAL_PASSWORD,
  SEED_SHOWCASE_STUDENT_PASSWORD,
  SEED_SHOWCASE_TEACHER_PASSWORD,
  SEED_SUPERADMIN_PASSWORD,
} from './seed-credentials'
import { db } from '../src/lib/db'
import { hashPassword } from '../src/lib/auth'

/**
 * seed — the HAWKINGS HIGH SCHOOL PRITHVIPUR base corpus (final
 * acceptance): school identity, principal, office, the 15-member
 * faculty, the 15-class / one-section academic skeleton with rooms, the
 * canonical subject set, and the deterministic 80-student roster with
 * guardians and account-level subscription locks.
 *
 * Determinism: the people corpus is generated by the PURE
 * prisma/hawkings-corpus.ts module (fixed seeds — identical output every
 * run, in every environment). Re-running this seed resets the demo
 * tenant to the canonical state (the same scoped-wipe discipline as
 * Phase 8A: everything EXCEPT the clean school is wiped and replanted).
 *
 * TENANT ID PRESERVATION: when a School row with the demo slug already
 * exists (e.g. the production transform, which pre-wipes dependent data
 * but deliberately keeps the row), the row is UPDATED in place — every
 * existing reference (audit history, platform ledger rows) stays
 * coherent. Local/CI runs recreate it fresh after the scoped wipe.
 *
 * Credentials: env-driven (prisma/seed-credentials.ts); NEVER printed.
 */

function initialAvatarSvg(name: string, seed: number): string {
  const parts = name.trim().split(/\s+/).filter(Boolean)
  const initials =
    parts.length === 0
      ? '?'
      : parts.length === 1
        ? parts[0].slice(0, 2).toUpperCase()
        : (parts[0][0] + parts[parts.length - 1][0]).toUpperCase()
  const hues = [160, 172, 184, 196, 24, 36, 8, 140, 210, 260, 320, 44]
  const hue = hues[seed % hues.length]
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96"><rect width="96" height="96" rx="20" fill="hsl(${hue}, 42%, 38%)"/><text x="48" y="58" font-family="Georgia, serif" font-size="34" font-weight="600" fill="#ffffff" text-anchor="middle">${initials}</text></svg>`
  return `data:image/svg+xml;base64,${Buffer.from(svg, 'utf8').toString('base64')}`
}

async function main() {
  // Phase 8A — shared seed lock (fail-safe, first statement). The single
  // sanctioned production exception is the deliberate demo-tenant
  // transform (explicit double opt-in — see seed-guard.ts).
  assertSeedable('seed')

  console.log('🌱 Seeding database — Hawkings High School Prithvipur…')

  // ── Phase 8A: wipe is scoped to the DEMO tenant plane ────────────────
  // Deterministic re-run: everything EXCEPT the clean school (green-valley,
  // planted by seed-clean.ts) and its users is hard-wiped and recreated —
  // `bun run seed:demo` resets the demo tenant to canonical state while
  // the clean tenant keeps its honest zeros. School-scoped tables not in
  // the list below (study materials, curriculum, exam marks, salary,
  // tenant domains, …) die via the School ON DELETE CASCADE when the
  // school rows go — EXCEPT on the production transform path, where the
  // pre-transform step already scoped-wiped the demo tenant's data and
  // kept the row (handled below by the reuse branch).
  const cleanSchool = await db.school.findUnique({ where: { slug: CLEAN_SCHOOL_SLUG } })
  const cleanUserIds = cleanSchool
    ? (await db.user.findMany({ where: { schoolId: cleanSchool.id }, select: { id: true } })).map((u) => u.id)
    : []
  const notCleanSchoolRows = cleanSchool ? { schoolId: { not: cleanSchool.id } } : {}
  const notCleanActivity = cleanSchool ? { OR: [{ schoolId: { not: cleanSchool.id } }, { schoolId: null }] } : {}
  const notCleanUsers = cleanSchool ? { id: { notIn: cleanUserIds } } : {}
  const notCleanSessions = cleanSchool ? { userId: { notIn: cleanUserIds } } : {}
  const notCleanSchools = cleanSchool ? { id: { not: cleanSchool.id } } : {}

  const isProdTransform =
    (process.env.DATABASE_ENV ?? '') === 'production' &&
    (process.env.SCHOLARIO_DEMO_TRANSFORM_CONSENT ?? '') === DEMO_TRANSFORM_CONSENT_LITERAL

  // On the production transform the School row itself is PRESERVED (the
  // pre-transform step wiped its dependent data) — skip the school-row
  // delete so every FK-free platform reference (audit ledger) stays
  // coherent with the same tenant id.
  if (!isProdTransform) {
    await db.feeTransaction.deleteMany({ where: notCleanSchoolRows })
    await db.payment.deleteMany({ where: notCleanSchoolRows })
    await db.bookIssue.deleteMany()
    await db.libraryBook.deleteMany({ where: notCleanSchoolRows })
    await db.notification.deleteMany({ where: notCleanSchoolRows })
    await db.assignment.deleteMany({ where: notCleanSchoolRows })
    await db.result.deleteMany()
    await db.examPaper.deleteMany({ where: notCleanSchoolRows })
    await db.questionBank.deleteMany({ where: notCleanSchoolRows })
    await db.exam.deleteMany({ where: notCleanSchoolRows })
    await db.attendance.deleteMany({ where: notCleanSchoolRows })
    await db.timetable.deleteMany({ where: notCleanSchoolRows })
    await db.fee.deleteMany({ where: notCleanSchoolRows })
    await db.vehicle.deleteMany({ where: notCleanSchoolRows })
    await db.route.deleteMany({ where: notCleanSchoolRows })
    await db.driver.deleteMany({ where: notCleanSchoolRows })
    await db.teacher.deleteMany({ where: notCleanSchoolRows })
    await db.student.deleteMany({ where: notCleanSchoolRows })
    await db.subject.deleteMany({ where: notCleanSchoolRows })
    await db.class.deleteMany({ where: notCleanSchoolRows })
    await db.room.deleteMany({ where: notCleanSchoolRows })
    await db.activityLog.deleteMany({ where: notCleanActivity })
    await db.session.deleteMany({ where: notCleanSessions })
    await db.message.deleteMany({ where: notCleanSchoolRows })
    await db.schoolEvent.deleteMany({ where: notCleanSchoolRows })
    await db.user.deleteMany({ where: notCleanUsers })
    await db.school.deleteMany({ where: notCleanSchools })
  }
  await db.platformSetting.deleteMany()

  // Initialize Platform Settings
  await db.platformSetting.create({
    data: {
      id: 'global',
      showDemoSchool: true,
    },
  })

  // ---------------- LEGACY SUPER ADMIN (platform migration path) --------
  // seed-platform.ts migrates these rows into PlatformAdmin and suspends
  // them; school login rejects the role outright (Phase 6 invariant).
  await db.user.upsert({
    where: { email: 'admin@erpsuite.io' },
    update: {},
    create: {
      email: 'admin@erpsuite.io',
      passwordHash: hashPassword(SEED_SUPERADMIN_PASSWORD),
      name: 'Platform Super Admin',
      role: 'SUPER_ADMIN',
      phone: '+91 90000 00000',
      status: 'ACTIVE',
    },
  })
  await db.user.upsert({
    where: { email: 'admin@scholario.cloud' },
    update: {},
    create: {
      email: 'admin@scholario.cloud',
      passwordHash: hashPassword(SEED_SUPERADMIN_PASSWORD),
      name: 'Arjun Malhotra',
      role: 'SUPER_ADMIN',
      phone: '+91 90000 00001',
      status: 'ACTIVE',
    },
  })

  // ---------------- HAWKINGS HIGH SCHOOL PRITHVIPUR (demo tenant) --------
  // Reuse the existing row when present (production transform keeps the
  // tenant id); plant the full canonical identity either way.
  const existingDemoSchool = await db.school.findUnique({ where: { slug: DEMO_SCHOOL_SLUG } })
  const demoSchool = existingDemoSchool
    ? await db.school.update({
        where: { id: existingDemoSchool.id },
        data: {
          name: DEMO_SCHOOL_NAME,
          slug: DEMO_SCHOOL_SLUG,
          code: DEMO_SCHOOL_CODE,
          domain: DEMO_SCHOOL_DOMAIN,
          address: 'Hawkings High School, Ward 3, Main Market Road, Prithvipur, Ghazipur, Uttar Pradesh — 233226, India',
          city: 'Prithvipur',
          phone: '+91 94152 22100',
          email: 'office@hawkingshigh.edu',
          themeColor: '#0f766e',
          accentColor: '#f59e0b',
          plan: 'ENTERPRISE',
          status: 'ACTIVE',
          academicYear: '2026-2027',
          board: 'CBSE',
          isDemo: true,
          featureFlags: '{}',
          shortName: 'Hawkings High',
          tagline: 'Knowledge · Character · Service',
          affiliation: 'CBSE (Patna Region)',
          website: 'https://hawkingshigh.edu',
          principalName: 'Dr. (Smt.) Sunita Verma',
          established: '2004',
          faviconUrl: null,
          settings: '{}',
          websiteContent: '{}',
        },
      })
    : await db.school.create({
        data: {
          name: DEMO_SCHOOL_NAME,
          slug: DEMO_SCHOOL_SLUG,
          code: DEMO_SCHOOL_CODE,
          domain: DEMO_SCHOOL_DOMAIN,
          address: 'Hawkings High School, Ward 3, Main Market Road, Prithvipur, Ghazipur, Uttar Pradesh — 233226, India',
          city: 'Prithvipur',
          phone: '+91 94152 22100',
          email: 'office@hawkingshigh.edu',
          themeColor: '#0f766e',
          accentColor: '#f59e0b',
          plan: 'ENTERPRISE',
          status: 'ACTIVE',
          academicYear: '2026-2027',
          board: 'CBSE',
          isDemo: true,
          shortName: 'Hawkings High',
          tagline: 'Knowledge · Character · Service',
          affiliation: 'CBSE (Patna Region)',
          website: 'https://hawkingshigh.edu',
          principalName: 'Dr. (Smt.) Sunita Verma',
          established: '2004',
        },
      })
  console.log(`  School: ${demoSchool.name} (${demoSchool.slug}, isDemo=${demoSchool.isDemo})${existingDemoSchool ? ' — tenant id preserved' : ''}`)

  // ── Principal + office (management) ──────────────────────────────────
  const principalUser = await db.user.upsert({
    where: { email: PRINCIPAL.email },
    update: {},
    create: {
      schoolId: demoSchool.id,
      email: PRINCIPAL.email,
      passwordHash: hashPassword(SEED_SHOWCASE_PRINCIPAL_PASSWORD),
      name: PRINCIPAL.name,
      role: 'PRINCIPAL',
      phone: PRINCIPAL.phone,
      status: 'ACTIVE',
    },
  })
  await db.user.upsert({
    where: { email: MANAGEMENT.email },
    update: {},
    create: {
      schoolId: demoSchool.id,
      email: MANAGEMENT.email,
      passwordHash: hashPassword(SEED_DEMO_PASSWORD),
      name: MANAGEMENT.name,
      role: 'MANAGEMENT',
      phone: MANAGEMENT.phone,
      status: 'ACTIVE',
    },
  })

  // ── Faculty: 15 teachers (users + Teacher rows) ───────────────────────
  const teacherUsers: { n: number; userId: string; name: string; email: string }[] = []
  for (const f of FACULTY) {
    const email = `teacher${f.n}@hawkingshigh.edu`
    const u = await db.user.upsert({
      where: { email },
      update: {},
      create: {
        schoolId: demoSchool.id,
        email,
        passwordHash: hashPassword(f.n === 1 ? SEED_SHOWCASE_TEACHER_PASSWORD : SEED_DEMO_PASSWORD),
        name: f.name,
        role: 'TEACHER',
        phone: f.phone,
        status: 'ACTIVE',
      },
    })
    await db.teacher.upsert({
      where: { userId: u.id },
      update: {},
      create: {
        schoolId: demoSchool.id,
        userId: u.id,
        employeeId: `HHS-T-${String(f.n).padStart(3, '0')}`,
        department: f.department,
        qualification: f.qualification,
        subjects: null,
      },
    })
    teacherUsers.push({ n: f.n, userId: u.id, name: f.name, email })
  }

  // ── Account-level subscription locks (Phase 10) ──────────────────────
  // Applied AFTER the roster exists (below) — see the lock section.

  // ── Rooms: 15 homerooms + special rooms ──────────────────────────────
  const roomByName = new Map<string, string>()
  for (const lv of DEMO_CLASS_LEVELS) {
    const existing = await db.room.findFirst({ where: { schoolId: demoSchool.id, name: lv.room } })
    const room = existing
      ? await db.room.update({ where: { id: existing.id }, data: { type: 'Classroom', capacity: lv.capacity, active: true, code: `RM-${lv.key}0A`, building: 'Main Building', floor: lv.key === 'Nursery' || lv.key === 'LKG' || lv.key === 'IKG' || lv.key === '1' || lv.key === '2' ? 'Ground' : 'First' } })
      : await db.room.create({ data: { schoolId: demoSchool.id, name: lv.room, code: `RM-${lv.key}0A`, type: 'Classroom', capacity: lv.capacity, building: 'Main Building', floor: Number(lv.key) <= 2 || !Number.isFinite(Number(lv.key)) ? 'Ground' : 'First' } })
    roomByName.set(lv.room, room.id)
  }
  for (const r of SPECIAL_ROOMS) {
    const existing = await db.room.findFirst({ where: { schoolId: demoSchool.id, name: r.name } })
    const room = existing
      ? await db.room.update({ where: { id: existing.id }, data: { type: r.type, capacity: r.capacity, active: true, code: r.code, building: 'Main Building' } })
      : await db.room.create({ data: { schoolId: demoSchool.id, name: r.name, code: r.code, type: r.type, capacity: r.capacity, building: 'Main Building' } })
    roomByName.set(r.name, room.id)
  }

  // ── Classes: 15 levels × one section (A) ─────────────────────────────
  const classIdByLevel = new Map<string, string>()
  for (const lv of DEMO_CLASS_LEVELS) {
    const classTeacher = teacherUsers.find((t) => String(t.n) === classTeacherForLevel(lv.key))
    const existing = await db.class.findFirst({ where: { schoolId: demoSchool.id, name: lv.label } })
    const cls = existing
      ? await db.class.update({
          where: { id: existing.id },
          data: {
            gradeLevel: lv.level,
            section: 'A',
            stream: lv.key === '11' || lv.key === '12' ? 'Science' : null,
            capacity: lv.capacity,
            roomId: roomByName.get(lv.room) ?? null,
            room: lv.room,
            classTeacherId: classTeacher?.userId ?? null,
          },
        })
      : await db.class.create({
          data: {
            schoolId: demoSchool.id,
            name: lv.label,
            gradeLevel: lv.level,
            section: 'A',
            stream: lv.key === '11' || lv.key === '12' ? 'Science' : null,
            capacity: lv.capacity,
            roomId: roomByName.get(lv.room) ?? null,
            room: lv.room,
            classTeacherId: classTeacher?.userId ?? null,
          },
        })
    classIdByLevel.set(lv.key, cls.id)
  }

  // Faculty N for each level's class teacher (hawkings-corpus FACULTY.
  // classTeacherOf). Local resolver to avoid an import cycle.
  function classTeacherForLevel(level: string): string {
    const f = FACULTY.find((t) => t.classTeacherOf === level)
    return f ? String(f.n) : '1'
  }

  // ── Canonical subjects (13, school-scoped) ───────────────────────────
  const subjectIdByCode = new Map<string, string>()
  for (const s of SUBJECTS) {
    const existing = await db.subject.findFirst({ where: { schoolId: demoSchool.id, code: s.code } })
    const row = existing
      ? await db.subject.update({ where: { id: existing.id }, data: { name: s.name, status: 'Active', fullMarks: 100, passMarks: 33, classId: null } })
      : await db.subject.create({ data: { schoolId: demoSchool.id, name: s.name, code: s.code, status: 'Active', fullMarks: 100, passMarks: 33 } })
    subjectIdByCode.set(s.code, row.id)
  }

  // ── The deterministic 80-student roster + guardians ──────────────────
  const roster = buildStudentRoster()
  const lockedStudentEmails = new Set(
    DEMO_SUBSCRIPTION_LOCKED_STUDENTS.map((p) => roster.find((s) => s.level === p.level && s.idx === p.idx)?.studentEmail).filter(Boolean) as string[],
  )
  const guardianIdByEmail = new Map<string, string>()
  let planted = 0
  for (const st of roster) {
    // Guardian (parent) account — one per family (siblings share).
    let guardianId = guardianIdByEmail.get(st.guardianEmail)
    if (!guardianId) {
      const existing = await db.user.findUnique({ where: { email: st.guardianEmail } })
      const gu = existing
        ? await db.user.update({ where: { id: existing.id }, data: { schoolId: demoSchool.id, name: st.guardianName, role: 'PARENT', phone: st.guardianPhone, status: 'ACTIVE', subscriptionStatus: 'ACTIVE' } })
        : await db.user.create({
            data: {
              schoolId: demoSchool.id,
              email: st.guardianEmail,
              passwordHash: hashPassword(SEED_DEMO_PASSWORD),
              name: st.guardianName,
              role: 'PARENT',
              phone: st.guardianPhone,
              status: 'ACTIVE',
            },
          })
      guardianId = gu.id
      guardianIdByEmail.set(st.guardianEmail, gu.id)
    }

    const existingStudentUser = await db.user.findUnique({ where: { email: st.studentEmail } })
    const u = existingStudentUser
      ? await db.user.update({
          where: { id: existingStudentUser.id },
          data: {
            schoolId: demoSchool.id,
            name: st.name,
            role: 'STUDENT',
            phone: st.studentPhone ?? st.guardianPhone,
            status: 'ACTIVE',
            // Phase 10 — account-level subscription lock
            subscriptionStatus: lockedStudentEmails.has(st.studentEmail) ? 'LOCKED' : 'ACTIVE',
            avatarUrl: null,
            avatar: null,
          },
        })
      : await db.user.create({
          data: {
            schoolId: demoSchool.id,
            email: st.studentEmail,
            passwordHash: hashPassword(
              st.studentEmail === roster.find((s) => s.level === DEMO_STUDENT_POSITION.level && s.idx === DEMO_STUDENT_POSITION.idx)?.studentEmail
                ? SEED_SHOWCASE_STUDENT_PASSWORD
                : SEED_DEMO_PASSWORD,
            ),
            name: st.name,
            role: 'STUDENT',
            phone: st.studentPhone ?? st.guardianPhone,
            status: 'ACTIVE',
            subscriptionStatus: lockedStudentEmails.has(st.studentEmail) ? 'LOCKED' : 'ACTIVE',
          },
        })

    const existingStudent = await db.student.findUnique({ where: { userId: u.id } })
    const studentData = {
      schoolId: demoSchool.id,
      userId: u.id,
      classId: classIdByLevel.get(st.level) ?? null,
      rollNo: st.rollNo,
      admissionNo: st.admissionNo,
      guardianId,
      guardianName: st.guardianName,
      guardianPhone: st.guardianPhone,
      dob: st.dob,
      gender: st.gender,
      bloodGroup: st.bloodGroup,
      address: st.address,
      routeId: null,
      photoDataUrl: initialAvatarSvg(st.name, planted + 7),
    }
    if (existingStudent) {
      await db.student.update({ where: { id: existingStudent.id }, data: studentData })
    } else {
      await db.student.create({ data: studentData })
    }
    planted++
  }
  console.log(`  Students: ${planted} (across ${DEMO_CLASS_LEVELS.length} classes, one section each)`)

  // Phase 10 — lock the designated TEACHER account (Meena Kumari, 3-A).
  const lockedTeacherEmail = `teacher${DEMO_SUBSCRIPTION_LOCKED_TEACHER_N}@hawkingshigh.edu`
  await db.user.update({
    where: { email: lockedTeacherEmail },
    data: { subscriptionStatus: 'LOCKED' },
  })
  console.log(`  Subscription-locked accounts: ${lockedStudentEmails.size} students + 1 teacher (${lockedTeacherEmail})`)

  // ── Library — an authentic small-school shelf ────────────────────────
  const books: [string, string, string, string, number][] = [
    ['Wings of Fire', 'A.P.J. Abdul Kalam', 'Biography', 'Universities Press', 4],
    ['Ignited Minds', 'A.P.J. Abdul Kalam', 'Inspiration', 'Penguin India', 3],
    ['Malgudi Days', 'R.K. Narayan', 'Fiction', 'Indian Thought Publications', 5],
    ['Godan', 'Munshi Premchand', 'Hindi Fiction', 'Lotus Press', 6],
    ['Madhushala', 'Harivansh Rai Bachchan', 'Hindi Poetry', 'Rajkamal Prakashan', 3],
    ['Gaban', 'Munshi Premchand', 'Hindi Fiction', 'Lotus Press', 4],
    ['Mathematics for Class 10', 'R.D. Sharma', 'Textbook', 'Dhanpat Rai', 12],
    ['Science for Class 9', 'NCERT', 'Textbook', 'NCERT', 15],
    ['Physics Part II — Class 12', 'NCERT', 'Textbook', 'NCERT', 10],
    ['A Brief History of Time', 'Stephen Hawking', 'Science', 'Bantam', 2],
    ['The Story of My Life', 'Helen Keller', 'Biography', 'Fingerprint! Publishing', 3],
    ['Panchatantra Tales', 'Vishnu Sharma', 'Children', 'Amar Chitra Katha', 8],
  ]
  for (const [title, author, cat, pub, copies] of books) {
    const existing = await db.libraryBook.findFirst({ where: { schoolId: demoSchool.id, title, author } })
    if (existing) {
      await db.libraryBook.update({ where: { id: existing.id }, data: { copies, available: copies } })
    } else {
      await db.libraryBook.create({ data: { schoolId: demoSchool.id, title, author, category: cat, publisher: pub, copies, available: copies } })
    }
  }

  // ── Announcements / notifications (published, tenant-visible) ────────
  const notifications: { title: string; message: string; audience: string; priority: string; daysAgo: number }[] = [
    { title: 'Half-Yearly Examination Results Declared', message: 'Half-Yearly Examination (September 2026) results are now available on the student portal. Marksheets can be collected from the school office after 20 October.', audience: 'ALL', priority: 'HIGH', daysAgo: 3 },
    { title: 'Periodic Assessment 2 — 14 to 18 December', message: 'Periodic Assessment 2 for classes 1 to 12 will be held from 14 to 18 December 2026. The syllabus has been shared by the subject teachers.', audience: 'ALL', priority: 'MEDIUM', daysAgo: 9 },
    { title: 'Term 2 Tuition Fee — Last Date 10 November', message: 'Parents are requested to deposit the Term 2 tuition fee at the school office or via UPI before 10 November 2026. A late fee of ₹50 per month applies thereafter.', audience: 'ALL', priority: 'HIGH', daysAgo: 14 },
    { title: 'Annual Day "Hawkings Utsav 2026" — 22 December', message: 'The school Annual Day will be celebrated on 22 December 2026 on the school ground. Rehearsals begin in the Games period from next week.', audience: 'ALL', priority: 'MEDIUM', daysAgo: 21 },
    { title: 'Admissions Open — Session 2027-28', message: 'Admissions for Nursery to Class 11 for the 2027-28 session are open at the school office from 10:00 AM to 2:00 PM. Registration fee ₹200.', audience: 'PUBLIC', priority: 'LOW', daysAgo: 30 },
  ]
  for (const n of notifications) {
    const existing = await db.notification.findFirst({ where: { schoolId: demoSchool.id, title: n.title } })
    const data = {
      schoolId: demoSchool.id,
      title: n.title,
      message: n.message,
      audience: n.audience,
      priority: n.priority,
      status: 'PUBLISHED',
      publishAt: new Date(Date.now() - n.daysAgo * 86400000),
      senderId: principalUser.id,
    }
    if (existing) await db.notification.update({ where: { id: existing.id }, data })
    else await db.notification.create({ data })
  }

  // ── Activity log (provenance) ────────────────────────────────────────
  await db.activityLog.create({
    data: {
      schoolId: demoSchool.id,
      userId: principalUser.id,
      action: 'SCHOOL_SETUP',
      detail: `${DEMO_SCHOOL_NAME} canonical corpus planted (final acceptance).`,
    },
  })

  console.log('✅ Seed complete!')
  console.log(`   Demo tenant: ${DEMO_SCHOOL_NAME} (isDemo) — ${planted} students, ${FACULTY.length} teachers.`)
  console.log('   Credentials are env-driven (prisma/seed-credentials.ts; override via')
  console.log('   SEED_* vars — see .env.example). Values are intentionally NOT printed.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
