import type { AdmissionApplication } from './types'
import {
  defaultInitialFormData,
  defaultInitialFeeData,
  defaultSectionReviews,
  iraSeedFormData,
} from './defaults'

/**
 * Seed admission applications — coherent demo records.
 *
 * Every applicant carries their OWN identity (unique Aadhaar, own parents,
 * own address). Documents are plain "uploaded" records — no invented OCR
 * scores, verifiers, or timestamps (spec §37). Submitted/approved apps
 * include the required Aadhaar document so the verification workspace
 * derives an honest, approvable status. The Aarush draft is a genuine
 * in-progress draft: partially filled, no documents yet.
 */

const aadhaarDoc = (name: string) =>
  ({ status: 'uploaded' as const, fileName: `${name}.pdf` })

export const initialApplications: AdmissionApplication[] = [
  {
    id: 'APP-2026-001',
    admissionNo: 'ADM-2026-0841',
    studentId: 'STU-2026-0841',
    rollNo: '01',
    regNo: 'REG-CBSE-2026-9012',
    applicantName: 'Ira Malhotra',
    className: 'Class 2',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-27',
    lastUpdatedDate: '2026-07-28',
    status: 'Submitted',
    formData: iraSeedFormData,
    feeData: defaultInitialFeeData,
    sectionReviews: defaultSectionReviews(),
    auditTrail: [
      { id: 'a1', timestamp: '2026-07-27 10:15 AM', action: 'Application Created', actor: 'Parent (Rajiv Malhotra)', notes: 'Wizard form initialized' },
      { id: 'a2', timestamp: '2026-07-27 10:30 AM', action: 'Submitted', actor: 'Parent (Rajiv Malhotra)', notes: 'Application submitted for admission verification' },
    ],
  },
  {
    id: 'APP-2026-002',
    admissionNo: 'ADM-2026-0842',
    studentId: 'STU-2026-0842',
    rollNo: '02',
    regNo: 'REG-CBSE-2026-9013',
    applicantName: 'Rohan Deshmukh',
    className: 'Grade 9',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-26',
    lastUpdatedDate: '2026-07-27',
    status: 'Under Review',
    formData: {
      ...defaultInitialFormData,
      admissionType: 'transfer',
      firstName: 'Rohan',
      lastName: 'Deshmukh',
      dob: '2011-02-11',
      gender: 'Male',
      bloodGroup: 'O+',
      category: 'General',
      aadhaarNo: '7312 4450 9126',
      fatherName: 'Sanjay Deshmukh',
      fatherOccupation: 'Civil Engineer',
      fatherPhone: '+91 98220 45111',
      motherName: 'Anjali Deshmukh',
      motherOccupation: 'Dietician',
      motherPhone: '+91 98220 45112',
      emergencyName: 'Sanjay Deshmukh',
      emergencyRelation: 'Father',
      emergencyPhone: '+91 98220 45111',
      currentAddress: 'B-14, Vasant Vihar',
      district: 'New Delhi',
      state: 'Delhi',
      city: 'New Delhi',
      pincode: '110057',
      permAddress: 'B-14, Vasant Vihar',
      permDistrict: 'New Delhi',
      permState: 'Delhi',
      permCity: 'New Delhi',
      permPincode: '110057',
      previousSchool: 'Delhi Public School, Vasant Kunj',
      previousLocation: 'New Delhi',
      previousBoard: 'CBSE',
      previousClass: 'Class 8',
      previousSection: 'C',
      previousYear: '2024–2025',
      tcStatus: 'uploaded',
      tcNumber: 'TC-DPS-2025-1104',
      reasonForLeaving: 'Relocation to Gurugram',
      className: 'Grade 9',
      section: 'A',
      docStatuses: {
        aadhaar: aadhaarDoc('Student_Aadhaar_Rohan'),
        tc: aadhaarDoc('TC_DPS_Rohan'),
      },
      photoUploaded: true,
    },
    feeData: defaultInitialFeeData,
    sectionReviews: {
      ...defaultSectionReviews(),
      previousSchool: { status: 'Needs Review', remarks: 'Previous Class IX registration code pending CBSE portal cross-check.' },
    },
    auditTrail: [
      { id: 'a3', timestamp: '2026-07-26 11:20 AM', action: 'Application Submitted', actor: 'Applicant Parent', notes: 'Submitted via Online Admission Portal' },
      { id: 'a4', timestamp: '2026-07-27 09:10 AM', action: 'Under Review', actor: 'Admission Officer (Dr. Iyer)', notes: 'Flagged Previous School record for CBSE portal cross-check' },
    ],
  },
  {
    id: 'APP-2026-003',
    admissionNo: 'ADM-2026-0843',
    studentId: 'STU-2026-0843',
    rollNo: '03',
    regNo: 'REG-CBSE-2026-9014',
    applicantName: 'Kavya Pillai',
    className: 'Class 1',
    section: 'B',
    academicSession: '2025–2026',
    submittedDate: '2026-07-25',
    lastUpdatedDate: '2026-07-27',
    status: 'Need Correction',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Kavya',
      lastName: 'Pillai',
      dob: '2019-04-19',
      gender: 'Female',
      bloodGroup: 'A+',
      category: 'General',
      aadhaarNo: '5501 8834 2276',
      fatherName: 'Ramesh Pillai',
      fatherOccupation: 'Bank Manager',
      fatherPhone: '+91 98450 22110',
      motherName: 'Lakshmi Pillai',
      motherOccupation: 'Teacher',
      motherPhone: '+91 98450 22111',
      emergencyName: 'Lakshmi Pillai',
      emergencyRelation: 'Mother',
      emergencyPhone: '+91 98450 22111',
      currentAddress: 'H-45, Sector 23',
      district: 'Gurugram',
      state: 'Haryana',
      city: 'Gurugram',
      pincode: '122015',
      permAddress: 'H-45, Sector 23',
      permDistrict: 'Gurugram',
      permState: 'Haryana',
      permCity: 'Gurugram',
      permPincode: '122015',
      className: 'Class 1',
      section: 'B',
      docStatuses: {
        aadhaar: aadhaarDoc('Student_Aadhaar_Kavya'),
        tc: { status: 'uploaded', fileName: 'TC_Kavya_scan.pdf' },
      },
      photoUploaded: true,
    },
    feeData: defaultInitialFeeData,
    sectionReviews: {
      ...defaultSectionReviews(),
      documents: { status: 'Needs Review', remarks: 'Transfer Certificate copy is blurry. Please upload clear scan.' },
    },
    generalRemarks: 'Document scan blurry. Please re-upload Transfer Certificate.',
    auditTrail: [
      { id: 'a5', timestamp: '2026-07-25 02:15 PM', action: 'Application Submitted', actor: 'Parent', notes: 'Form submitted' },
      { id: 'a6', timestamp: '2026-07-27 10:00 AM', action: 'Returned for Correction', actor: 'Admission Desk', notes: 'Flagged documents section for re-upload' },
    ],
  },
  {
    id: 'APP-2026-004',
    admissionNo: 'ADM-2026-0844',
    studentId: 'STU-2026-0844',
    rollNo: '04',
    regNo: 'REG-CBSE-2026-9015',
    applicantName: 'Devansh Verma',
    className: 'Class 3',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-24',
    lastUpdatedDate: '2026-07-27',
    status: 'Approved',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Devansh',
      lastName: 'Verma',
      dob: '2017-11-30',
      gender: 'Male',
      bloodGroup: 'B+',
      category: 'OBC',
      aadhaarNo: '6620 1174 9038',
      fatherName: 'Alok Verma',
      fatherOccupation: 'Businessman',
      fatherPhone: '+91 98110 33445',
      motherName: 'Rekha Verma',
      motherOccupation: 'Homemaker',
      motherPhone: '+91 98110 33446',
      emergencyName: 'Alok Verma',
      emergencyRelation: 'Father',
      emergencyPhone: '+91 98110 33445',
      currentAddress: 'D-201, Sushant Lok Phase 1',
      district: 'Gurugram',
      state: 'Haryana',
      city: 'Gurugram',
      pincode: '122009',
      permAddress: 'D-201, Sushant Lok Phase 1',
      permDistrict: 'Gurugram',
      permState: 'Haryana',
      permCity: 'Gurugram',
      permPincode: '122009',
      className: 'Class 3',
      section: 'A',
      docStatuses: {
        aadhaar: aadhaarDoc('Student_Aadhaar_Devansh'),
      },
      photoUploaded: true,
    },
    feeData: defaultInitialFeeData,
    sectionReviews: defaultSectionReviews(),
    decisionBy: 'Principal Dr. Ananya Iyer',
    decisionDate: '2026-07-27',
    auditTrail: [
      { id: 'a7', timestamp: '2026-07-24 04:30 PM', action: 'Submitted', actor: 'Parent', notes: 'Form submitted' },
      { id: 'a8', timestamp: '2026-07-27 11:45 AM', action: 'Approved', actor: 'Principal Dr. Ananya Iyer', notes: 'All documents verified & principal interview cleared' },
    ],
  },
  {
    id: 'APP-2026-005',
    admissionNo: 'ADM-2026-0845',
    studentId: 'STU-2026-0845',
    rollNo: '05',
    regNo: 'REG-CBSE-2026-9016',
    applicantName: 'Siddharth Saxena',
    className: 'Grade 10',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-20',
    lastUpdatedDate: '2026-07-22',
    status: 'Rejected',
    formData: {
      ...defaultInitialFormData,
      admissionType: 'transfer',
      firstName: 'Siddharth',
      lastName: 'Saxena',
      dob: '2010-09-09',
      gender: 'Male',
      bloodGroup: 'AB+',
      category: 'General',
      aadhaarNo: '8890 2245 6613',
      fatherName: 'Vipul Saxena',
      fatherOccupation: 'Advocate',
      fatherPhone: '+91 99100 87654',
      motherName: 'Nidhi Saxena',
      motherOccupation: 'Architect',
      motherPhone: '+91 99100 87655',
      emergencyName: 'Vipul Saxena',
      emergencyRelation: 'Father',
      emergencyPhone: '+91 99100 87654',
      currentAddress: 'E-92, Defence Colony',
      district: 'New Delhi',
      state: 'Delhi',
      city: 'New Delhi',
      pincode: '110024',
      permAddress: 'E-92, Defence Colony',
      permDistrict: 'New Delhi',
      permState: 'Delhi',
      permCity: 'New Delhi',
      permPincode: '110024',
      previousSchool: 'Modern School, Barakhamba Road',
      previousBoard: 'CBSE',
      previousClass: 'Class 9',
      previousYear: '2024–2025',
      tcStatus: 'pending',
      className: 'Grade 10',
      section: 'A',
      docStatuses: {
        aadhaar: aadhaarDoc('Student_Aadhaar_Siddharth'),
      },
      photoUploaded: true,
    },
    feeData: defaultInitialFeeData,
    sectionReviews: {
      ...defaultSectionReviews(),
      classAllocation: { status: 'Incomplete', remarks: 'Grade 10 CBSE transfer seats quota exhausted for session.' },
    },
    decisionReason: 'Class 10 CBSE seat capacity limit reached for current session.',
    decisionBy: 'Admission Committee',
    decisionDate: '2026-07-22',
    rejectionRetentionDays: 60,
    rejectedAt: '2026-07-22',
    auditTrail: [
      { id: 'a9', timestamp: '2026-07-20 01:00 PM', action: 'Submitted', actor: 'Parent', notes: 'Submitted for Grade 10' },
      { id: 'a10', timestamp: '2026-07-22 03:20 PM', action: 'Rejected', actor: 'Admission Committee', notes: 'Seat limit reached for Grade 10' },
    ],
  },
  {
    id: 'APP-2026-006',
    admissionNo: 'ADM-2026-0840',
    studentId: 'STU-2026-0840',
    rollNo: '19',
    regNo: 'REG-CBSE-2026-9010',
    applicantName: 'Ananya Sharma',
    className: 'Class 2',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-15',
    lastUpdatedDate: '2026-07-18',
    status: 'Completed',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Ananya',
      lastName: 'Sharma',
      dob: '2017-05-25',
      gender: 'Female',
      bloodGroup: 'O+',
      category: 'General',
      aadhaarNo: '3345 9910 7742',
      fatherName: 'Manish Sharma',
      fatherOccupation: 'Chartered Accountant',
      fatherPhone: '+91 98100 47821',
      motherName: 'Kavita Sharma',
      motherOccupation: 'Doctor',
      motherPhone: '+91 98100 47822',
      emergencyName: 'Kavita Sharma',
      emergencyRelation: 'Mother',
      emergencyPhone: '+91 98100 47822',
      currentAddress: 'C-12, DLF Phase 3',
      district: 'Gurugram',
      state: 'Haryana',
      city: 'Gurugram',
      pincode: '122002',
      permAddress: 'C-12, DLF Phase 3',
      permDistrict: 'Gurugram',
      permState: 'Haryana',
      permCity: 'Gurugram',
      permPincode: '122002',
      className: 'Class 2',
      section: 'A',
      docStatuses: {
        aadhaar: aadhaarDoc('Student_Aadhaar_Ananya'),
      },
      photoUploaded: true,
    },
    feeData: defaultInitialFeeData,
    sectionReviews: defaultSectionReviews(),
    decisionBy: 'Principal Dr. Ananya Iyer',
    decisionDate: '2026-07-18',
    auditTrail: [
      { id: 'a11', timestamp: '2026-07-15 10:00 AM', action: 'Submitted', actor: 'Parent', notes: 'Submitted' },
      { id: 'a12', timestamp: '2026-07-18 02:00 PM', action: 'Admission Completed & Enrolled', actor: 'Admission Desk', notes: 'Official credentials & letter issued' },
    ],
    // FINAL-GATE: generatedCredentials (fabricated portal login) retired
    // from the seed record — portal accounts are provisioned by the real
    // Students & Classes enrolment flow. Dispatch flags stay false: the
    // seed records no notification dispatch (nothing was ever sent).
    notificationsSent: {
      sms: false,
      email: false,
      whatsapp: false,
    },
  },
  {
    id: 'APP-2026-007',
    admissionNo: 'ADM-DRAFT-007',
    studentId: 'STU-DRAFT-007',
    rollNo: '—',
    regNo: '—',
    applicantName: 'Aarush Goel',
    className: 'Nursery',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-28',
    lastUpdatedDate: '2026-07-28',
    status: 'Draft',
    // A genuine in-progress draft: partially filled by the parent,
    // nothing uploaded yet, no photo, no Aadhaar entered so far.
    formData: {
      ...defaultInitialFormData,
      firstName: 'Aarush',
      lastName: 'Goel',
      dob: '2022-12-06',
      gender: 'Male',
      fatherName: 'Pankaj Goel',
      fatherPhone: '+91 98100 47821',
      motherName: 'Richa Goel',
      className: 'Nursery',
      section: 'A',
      currentAddress: 'F-8, South City 1',
      district: 'Gurugram',
      state: 'Haryana',
      pincode: '122001',
    },
    feeData: defaultInitialFeeData,
    sectionReviews: defaultSectionReviews(),
    auditTrail: [
      { id: 'a13', timestamp: '2026-07-28 08:30 AM', action: 'Draft Created', actor: 'Applicant Parent', notes: 'Application saved as draft' },
    ],
  },
]
